export type GameCategory = 
  | 'guess-me'
  | 'would-you-rather'
  | 'who-knows-who'
  | 'make-me-laugh'
  | 'mini-debate'
  | 'draw-it'
  | 'memory'
  | 'trivia'
  | 'deep-thoughts'
  | 'chaos'

export type RoundType = 
  | 'simultaneous-choice'
  | 'would-you-rather'
  | 'text-guess'
  | 'timed-action'
  | 'debate'
  | 'drawing'
  | 'memory'
  | 'trivia'
  | 'text-input'
  | 'chaos'

export type Difficulty = 'chill' | 'chaotic' | 'unhinged'

export interface Round {
  id: number
  category: GameCategory
  title: string
  prompt: string
  choices?: string[]
  correctAnswer?: string | number
  type: RoundType
  timer?: number
  points: number
  difficulty: Difficulty
  bothPlayers: boolean
  instructions?: string
}

export const ROUNDS: Round[] = [
  // GUESS ME (1-10)
  {
    id: 1,
    category: 'guess-me',
    title: 'Guess Me',
    prompt: 'Which superpower would the other player choose?',
    choices: ['Teleportation', 'Flying', 'Reading minds', 'Time travel'],
    type: 'simultaneous-choice',
    timer: 30,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 2,
    category: 'guess-me',
    title: 'Guess Me',
    prompt: 'Which animal would the other player most want as a pet?',
    choices: ['Capybara', 'Penguin', 'Monkey', 'Miniature horse'],
    type: 'simultaneous-choice',
    timer: 30,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 3,
    category: 'guess-me',
    title: 'Guess Me',
    prompt: 'Which food could the other player eat forever?',
    choices: ['Pizza', 'Tacos', 'Pasta', 'Burgers'],
    type: 'simultaneous-choice',
    timer: 30,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 4,
    category: 'guess-me',
    title: 'Guess Me',
    prompt: 'Which fictional universe would the other player live in?',
    choices: ['Harry Potter', 'Star Wars', 'Pokémon', 'The Lord of the Rings'],
    type: 'simultaneous-choice',
    timer: 30,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 5,
    category: 'guess-me',
    title: 'Guess Me',
    prompt: 'Which job would the other player secretly enjoy?',
    choices: ['Detective', 'Chef', 'Professional gamer', 'Wildlife photographer'],
    type: 'simultaneous-choice',
    timer: 30,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 6,
    category: 'guess-me',
    title: 'Guess Me',
    prompt: 'Which object would the other player save first in a ridiculous house fire?',
    choices: ['Phone', 'Laptop', 'Favorite shoes', 'Something completely random'],
    type: 'simultaneous-choice',
    timer: 30,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 7,
    category: 'guess-me',
    title: 'Guess Me',
    prompt: 'What would the other player spend \$1,000 on?',
    choices: ['Travel', 'Food', 'Technology', 'Something irresponsible'],
    type: 'simultaneous-choice',
    timer: 30,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 8,
    category: 'guess-me',
    title: 'Guess Me',
    prompt: 'Which fictional character would the other player be friends with?',
    choices: ['Shrek', 'Batman', 'SpongeBob', 'Wednesday Addams'],
    type: 'simultaneous-choice',
    timer: 30,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 9,
    category: 'guess-me',
    title: 'Guess Me',
    prompt: 'Which would the other player choose?',
    choices: ['Sunrise', 'Sunset'],
    type: 'simultaneous-choice',
    timer: 30,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 10,
    category: 'guess-me',
    title: 'Guess Me',
    prompt: 'Which would the other player rather have?',
    choices: ['Unlimited money', 'Unlimited free travel'],
    type: 'simultaneous-choice',
    timer: 30,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },

  // WOULD YOU RATHER (11-20)
  {
    id: 11,
    category: 'would-you-rather',
    title: 'Would You Rather',
    prompt: 'Would you rather have a personal chef or personal driver?',
    choices: ['Personal chef', 'Personal driver'],
    type: 'simultaneous-choice',
    timer: 30,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 12,
    category: 'would-you-rather',
    title: 'Would You Rather',
    prompt: 'Would you rather live in a giant treehouse or a futuristic apartment?',
    choices: ['Giant treehouse', 'Futuristic apartment'],
    type: 'simultaneous-choice',
    timer: 30,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 13,
    category: 'would-you-rather',
    title: 'Would You Rather',
    prompt: 'Would you rather speak every language or play every instrument?',
    choices: ['Speak every language', 'Play every instrument'],
    type: 'simultaneous-choice',
    timer: 30,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 14,
    category: 'would-you-rather',
    title: 'Would You Rather',
    prompt: 'Would you rather never wait in line again or never sit in traffic again?',
    choices: ['Never wait in line', 'Never sit in traffic'],
    type: 'simultaneous-choice',
    timer: 30,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 15,
    category: 'would-you-rather',
    title: 'Would You Rather',
    prompt: 'Would you rather be able to pause time or rewind five minutes?',
    choices: ['Pause time', 'Rewind five minutes'],
    type: 'simultaneous-choice',
    timer: 30,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 16,
    category: 'would-you-rather',
    title: 'Would You Rather',
    prompt: 'Would you rather have a pet dragon or a pet dinosaur?',
    choices: ['Pet dragon', 'Pet dinosaur'],
    type: 'simultaneous-choice',
    timer: 30,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 17,
    category: 'would-you-rather',
    title: 'Would You Rather',
    prompt: 'Would you rather explore the deepest ocean or outer space?',
    choices: ['Deepest ocean', 'Outer space'],
    type: 'simultaneous-choice',
    timer: 30,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 18,
    category: 'would-you-rather',
    title: 'Would You Rather',
    prompt: 'Would you rather always know when someone is lying or always know what people genuinely think of you?',
    choices: ['Know when lying', 'Know what people think'],
    type: 'simultaneous-choice',
    timer: 30,
    points: 100,
    difficulty: 'chaotic',
    bothPlayers: true,
  },
  {
    id: 19,
    category: 'would-you-rather',
    title: 'Would You Rather',
    prompt: 'Would you rather have perfect memory or perfect creativity?',
    choices: ['Perfect memory', 'Perfect creativity'],
    type: 'simultaneous-choice',
    timer: 30,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 20,
    category: 'would-you-rather',
    title: 'Would You Rather',
    prompt: 'Would you rather live without social media or without television?',
    choices: ['No social media', 'No television'],
    type: 'simultaneous-choice',
    timer: 30,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },

  // WHO KNOWS WHO (21-30)
  {
    id: 21,
    category: 'who-knows-who',
    title: 'Who Knows Who',
    prompt: 'What is the other player\'s ideal lazy Sunday?',
    type: 'text-guess',
    timer: 45,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 22,
    category: 'who-knows-who',
    title: 'Who Knows Who',
    prompt: 'What would the other player order at a restaurant?',
    type: 'text-guess',
    timer: 45,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 23,
    category: 'who-knows-who',
    title: 'Who Knows Who',
    prompt: 'What would instantly improve the other player\'s mood?',
    type: 'text-guess',
    timer: 45,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 24,
    category: 'who-knows-who',
    title: 'Who Knows Who',
    prompt: 'What is the other player\'s most-used phrase?',
    type: 'text-guess',
    timer: 45,
    points: 100,
    difficulty: 'chaotic',
    bothPlayers: true,
  },
  {
    id: 25,
    category: 'who-knows-who',
    title: 'Who Knows Who',
    prompt: 'What would the other player buy if they suddenly became rich?',
    type: 'text-guess',
    timer: 45,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 26,
    category: 'who-knows-who',
    title: 'Who Knows Who',
    prompt: 'What is the other player\'s dream holiday destination?',
    type: 'text-guess',
    timer: 45,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 27,
    category: 'who-knows-who',
    title: 'Who Knows Who',
    prompt: 'What would the other player bring to a deserted island?',
    type: 'text-guess',
    timer: 45,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 28,
    category: 'who-knows-who',
    title: 'Who Knows Who',
    prompt: 'What is the other player\'s most likely irrational fear?',
    type: 'text-guess',
    timer: 45,
    points: 100,
    difficulty: 'chaotic',
    bothPlayers: true,
  },
  {
    id: 29,
    category: 'who-knows-who',
    title: 'Who Knows Who',
    prompt: 'What would the other player name a spaceship?',
    type: 'text-guess',
    timer: 45,
    points: 100,
    difficulty: 'chaotic',
    bothPlayers: true,
  },
  {
    id: 30,
    category: 'who-knows-who',
    title: 'Who Knows Who',
    prompt: 'What is the other player\'s perfect movie-night snack?',
    type: 'text-guess',
    timer: 45,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },

  // MAKE ME LAUGH (31-40)
  {
    id: 31,
    category: 'make-me-laugh',
    title: 'Make Me Laugh',
    prompt: 'Make the other player laugh without saying the word "laugh".',
    instructions: 'You have 30 seconds. The other player wins if they laugh!',
    type: 'timed-action',
    timer: 30,
    points: 100,
    difficulty: 'chaotic',
    bothPlayers: false,
  },
  {
    id: 32,
    category: 'make-me-laugh',
    title: 'Make Me Laugh',
    prompt: 'Invent the world\'s worst superhero.',
    instructions: 'You have 30 seconds to describe them.',
    type: 'timed-action',
    timer: 30,
    points: 100,
    difficulty: 'chaotic',
    bothPlayers: false,
  },
  {
    id: 33,
    category: 'make-me-laugh',
    title: 'Make Me Laugh',
    prompt: 'Give the most ridiculous motivational speech possible.',
    instructions: 'You have 30 seconds. Make them believe.',
    type: 'timed-action',
    timer: 30,
    points: 100,
    difficulty: 'unhinged',
    bothPlayers: false,
  },
  {
    id: 34,
    category: 'make-me-laugh',
    title: 'Make Me Laugh',
    prompt: 'Sell a completely useless product like you\'re on television.',
    instructions: 'You have 30 seconds to pitch it.',
    type: 'timed-action',
    timer: 30,
    points: 100,
    difficulty: 'chaotic',
    bothPlayers: false,
  },
  {
    id: 35,
    category: 'make-me-laugh',
    title: 'Make Me Laugh',
    prompt: 'Imitate a dramatic movie trailer for your current situation.',
    instructions: 'You have 30 seconds. Make it epic.',
    type: 'timed-action',
    timer: 30,
    points: 100,
    difficulty: 'chaotic',
    bothPlayers: false,
  },
  {
    id: 36,
    category: 'make-me-laugh',
    title: 'Make Me Laugh',
    prompt: 'Explain how to make a sandwich like you\'re a scientist.',
    instructions: 'You have 30 seconds.',
    type: 'timed-action',
    timer: 30,
    points: 100,
    difficulty: 'chill',
    bothPlayers: false,
  },
  {
    id: 37,
    category: 'make-me-laugh',
    title: 'Make Me Laugh',
    prompt: 'Give yourself an absurd new celebrity name.',
    instructions: 'You have 30 seconds to explain why.',
    type: 'timed-action',
    timer: 30,
    points: 100,
    difficulty: 'chaotic',
    bothPlayers: false,
  },
  {
    id: 38,
    category: 'make-me-laugh',
    title: 'Make Me Laugh',
    prompt: 'Invent a terrible theme park attraction.',
    instructions: 'You have 30 seconds to describe it.',
    type: 'timed-action',
    timer: 30,
    points: 100,
    difficulty: 'chaotic',
    bothPlayers: false,
  },
  {
    id: 39,
    category: 'make-me-laugh',
    title: 'Make Me Laugh',
    prompt: 'Describe the other player as if they were a nature documentary.',
    instructions: 'You have 30 seconds. David Attenborough style.',
    type: 'timed-action',
    timer: 30,
    points: 100,
    difficulty: 'unhinged',
    bothPlayers: false,
  },
  {
    id: 40,
    category: 'make-me-laugh',
    title: 'Make Me Laugh',
    prompt: 'Give a serious weather report about the room you\'re sitting in.',
    instructions: 'You have 30 seconds.',
    type: 'timed-action',
    timer: 30,
    points: 100,
    difficulty: 'chill',
    bothPlayers: false,
  },

  // MINI DEBATE (41-50)
  {
    id: 41,
    category: 'mini-debate',
    title: 'Mini Debate',
    prompt: 'Cereal is soup.',
    instructions: '30 seconds per player to argue. Then vote on who was more convincing.',
    type: 'debate',
    timer: 30,
    points: 100,
    difficulty: 'chaotic',
    bothPlayers: true,
  },
  {
    id: 42,
    category: 'mini-debate',
    title: 'Mini Debate',
    prompt: 'Aliens would love fast food.',
    instructions: '30 seconds per player to argue.',
    type: 'debate',
    timer: 30,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 43,
    category: 'mini-debate',
    title: 'Mini Debate',
    prompt: 'Pigeons probably know more than they let on.',
    instructions: '30 seconds per player to argue.',
    type: 'debate',
    timer: 30,
    points: 100,
    difficulty: 'chaotic',
    bothPlayers: true,
  },
  {
    id: 44,
    category: 'mini-debate',
    title: 'Mini Debate',
    prompt: 'Running is just controlled falling.',
    instructions: '30 seconds per player to argue.',
    type: 'debate',
    timer: 30,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 45,
    category: 'mini-debate',
    title: 'Mini Debate',
    prompt: 'Toast is a form of cooked bread.',
    instructions: '30 seconds per player to argue.',
    type: 'debate',
    timer: 30,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 46,
    category: 'mini-debate',
    title: 'Mini Debate',
    prompt: 'Hot dogs should legally be considered sandwiches.',
    instructions: '30 seconds per player to argue.',
    type: 'debate',
    timer: 30,
    points: 100,
    difficulty: 'chaotic',
    bothPlayers: true,
  },
  {
    id: 47,
    category: 'mini-debate',
    title: 'Mini Debate',
    prompt: 'Monday should be removed from the calendar.',
    instructions: '30 seconds per player to argue.',
    type: 'debate',
    timer: 30,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 48,
    category: 'mini-debate',
    title: 'Mini Debate',
    prompt: 'Every adult needs recess.',
    instructions: '30 seconds per player to argue.',
    type: 'debate',
    timer: 30,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 49,
    category: 'mini-debate',
    title: 'Mini Debate',
    prompt: 'An octopus would make a better roommate than a cat.',
    instructions: '30 seconds per player to argue.',
    type: 'debate',
    timer: 30,
    points: 100,
    difficulty: 'chaotic',
    bothPlayers: true,
  },
  {
    id: 50,
    category: 'mini-debate',
    title: 'Mini Debate',
    prompt: 'Plants secretly judge us.',
    instructions: '30 seconds per player to argue.',
    type: 'debate',
    timer: 30,
    points: 100,
    difficulty: 'unhinged',
    bothPlayers: true,
  },

  // DRAW IT (51-60)
  {
    id: 51,
    category: 'draw-it',
    title: 'Draw It',
    prompt: 'A UFO landing in a supermarket',
    instructions: 'One player draws, the other guesses. You have 45 seconds!',
    type: 'drawing',
    timer: 45,
    points: 150,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 52,
    category: 'draw-it',
    title: 'Draw It',
    prompt: 'A cat running a restaurant',
    type: 'drawing',
    timer: 45,
    points: 150,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 53,
    category: 'draw-it',
    title: 'Draw It',
    prompt: 'A dinosaur on vacation',
    type: 'drawing',
    timer: 45,
    points: 150,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 54,
    category: 'draw-it',
    title: 'Draw It',
    prompt: 'A robot having a terrible day',
    type: 'drawing',
    timer: 45,
    points: 150,
    difficulty: 'chaotic',
    bothPlayers: true,
  },
  {
    id: 55,
    category: 'draw-it',
    title: 'Draw It',
    prompt: 'An alien trying to use a vending machine',
    type: 'drawing',
    timer: 45,
    points: 150,
    difficulty: 'chaotic',
    bothPlayers: true,
  },
  {
    id: 56,
    category: 'draw-it',
    title: 'Draw It',
    prompt: 'A haunted pizza',
    type: 'drawing',
    timer: 45,
    points: 150,
    difficulty: 'chaotic',
    bothPlayers: true,
  },
  {
    id: 57,
    category: 'draw-it',
    title: 'Draw It',
    prompt: 'A very confused wizard',
    type: 'drawing',
    timer: 45,
    points: 150,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 58,
    category: 'draw-it',
    title: 'Draw It',
    prompt: 'A frog becoming famous',
    type: 'drawing',
    timer: 45,
    points: 150,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 59,
    category: 'draw-it',
    title: 'Draw It',
    prompt: 'Your dream house',
    type: 'drawing',
    timer: 45,
    points: 150,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 60,
    category: 'draw-it',
    title: 'Draw It',
    prompt: 'The world\'s worst invention',
    type: 'drawing',
    timer: 45,
    points: 150,
    difficulty: 'unhinged',
    bothPlayers: true,
  },

  // MEMORY (61-70)
  {
    id: 61,
    category: 'memory',
    title: 'Memory',
    prompt: '🍕 🐸 🚀 🧠 🌵',
    instructions: 'Memorize the sequence. After it hides, recreate it!',
    type: 'memory',
    timer: 5,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 62,
    category: 'memory',
    title: 'Memory',
    prompt: '🌈 👽 🍔 🐱 🎸',
    type: 'memory',
    timer: 5,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 63,
    category: 'memory',
    title: 'Memory',
    prompt: '🚲 🌙 🍩 🦖 🎮',
    type: 'memory',
    timer: 5,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 64,
    category: 'memory',
    title: 'Memory',
    prompt: '🐸 🛸 🍕 👻 🌴',
    type: 'memory',
    timer: 5,
    points: 100,
    difficulty: 'chaotic',
    bothPlayers: true,
  },
  {
    id: 65,
    category: 'memory',
    title: 'Memory',
    prompt: '🎸 🧠 🐙 🍪 🚀',
    type: 'memory',
    timer: 5,
    points: 100,
    difficulty: 'chaotic',
    bothPlayers: true,
  },
  {
    id: 66,
    category: 'memory',
    title: 'Memory',
    prompt: '🌵 🎮 🦄 🍔 🌙',
    type: 'memory',
    timer: 5,
    points: 100,
    difficulty: 'chaotic',
    bothPlayers: true,
  },
  {
    id: 67,
    category: 'memory',
    title: 'Memory',
    prompt: '👻 🍕 🐸 🎸 🛸',
    type: 'memory',
    timer: 5,
    points: 100,
    difficulty: 'chaotic',
    bothPlayers: true,
  },
  {
    id: 68,
    category: 'memory',
    title: 'Memory',
    prompt: '🐱 🚀 🍩 🧠 🌈',
    type: 'memory',
    timer: 5,
    points: 100,
    difficulty: 'unhinged',
    bothPlayers: true,
  },
  {
    id: 69,
    category: 'memory',
    title: 'Memory',
    prompt: '🦖 🍔 🌴 🎮 👽',
    type: 'memory',
    timer: 5,
    points: 100,
    difficulty: 'unhinged',
    bothPlayers: true,
  },
  {
    id: 70,
    category: 'memory',
    title: 'Memory',
    prompt: '🍪 🐙 🌙 🦄 🚲',
    type: 'memory',
    timer: 5,
    points: 100,
    difficulty: 'unhinged',
    bothPlayers: true,
  },

  // TRIVIA (71-80)
  {
    id: 71,
    category: 'trivia',
    title: 'Trivia',
    prompt: 'How many hearts does an octopus have?',
    choices: ['1', '2', '3', '8'],
    correctAnswer: 2,
    type: 'trivia',
    timer: 30,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 72,
    category: 'trivia',
    title: 'Trivia',
    prompt: 'Which planet has the most prominent ring system?',
    choices: ['Mars', 'Saturn', 'Venus', 'Mercury'],
    correctAnswer: 1,
    type: 'trivia',
    timer: 30,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 73,
    category: 'trivia',
    title: 'Trivia',
    prompt: 'How many sides does a hexagon have?',
    choices: ['5', '6', '7', '8'],
    correctAnswer: 1,
    type: 'trivia',
    timer: 30,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 74,
    category: 'trivia',
    title: 'Trivia',
    prompt: 'Which animal is known for having fingerprints very similar to humans?',
    choices: ['Koala', 'Elephant', 'Penguin', 'Tiger'],
    correctAnswer: 0,
    type: 'trivia',
    timer: 30,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 75,
    category: 'trivia',
    title: 'Trivia',
    prompt: 'What is the largest planet in our solar system?',
    choices: ['Earth', 'Saturn', 'Jupiter', 'Neptune'],
    correctAnswer: 2,
    type: 'trivia',
    timer: 30,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 76,
    category: 'trivia',
    title: 'Trivia',
    prompt: 'How many minutes are in two hours?',
    choices: ['60', '90', '120', '180'],
    correctAnswer: 2,
    type: 'trivia',
    timer: 30,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 77,
    category: 'trivia',
    title: 'Trivia',
    prompt: 'Which ocean is the largest?',
    choices: ['Atlantic', 'Indian', 'Arctic', 'Pacific'],
    correctAnswer: 3,
    type: 'trivia',
    timer: 30,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 78,
    category: 'trivia',
    title: 'Trivia',
    prompt: 'How many colors are traditionally listed in a rainbow?',
    choices: ['5', '6', '7', '8'],
    correctAnswer: 2,
    type: 'trivia',
    timer: 30,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 79,
    category: 'trivia',
    title: 'Trivia',
    prompt: 'Which animal is the largest land animal?',
    choices: ['Rhinoceros', 'Elephant', 'Giraffe', 'Hippopotamus'],
    correctAnswer: 1,
    type: 'trivia',
    timer: 30,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 80,
    category: 'trivia',
    title: 'Trivia',
    prompt: 'Which instrument usually has black and white keys?',
    choices: ['Violin', 'Piano', 'Trumpet', 'Flute'],
    correctAnswer: 1,
    type: 'trivia',
    timer: 30,
    points: 100,
    difficulty: 'chill',
    bothPlayers: true,
  },

  // DEEP THOUGHTS (81-90)
  {
    id: 81,
    category: 'deep-thoughts',
    title: 'Deep Thoughts',
    prompt: 'What is something tiny that instantly makes your day better?',
    instructions: 'Share openly. You can always skip.',
    type: 'text-input',
    points: 0,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 82,
    category: 'deep-thoughts',
    title: 'Deep Thoughts',
    prompt: 'What is a completely useless skill you\'re proud of?',
    type: 'text-input',
    points: 0,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 83,
    category: 'deep-thoughts',
    title: 'Deep Thoughts',
    prompt: 'What fictional world would you visit for one day?',
    type: 'text-input',
    points: 0,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 84,
    category: 'deep-thoughts',
    title: 'Deep Thoughts',
    prompt: 'What is a childhood belief you had that makes you laugh now?',
    type: 'text-input',
    points: 0,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 85,
    category: 'deep-thoughts',
    title: 'Deep Thoughts',
    prompt: 'What is one thing you think everyone should experience once?',
    type: 'text-input',
    points: 0,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 86,
    category: 'deep-thoughts',
    title: 'Deep Thoughts',
    prompt: 'What random memory do you remember unusually well?',
    type: 'text-input',
    points: 0,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 87,
    category: 'deep-thoughts',
    title: 'Deep Thoughts',
    prompt: 'What would your perfect no-responsibilities day look like?',
    type: 'text-input',
    points: 0,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 88,
    category: 'deep-thoughts',
    title: 'Deep Thoughts',
    prompt: 'What is something you would learn purely because it sounds fun?',
    type: 'text-input',
    points: 0,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 89,
    category: 'deep-thoughts',
    title: 'Deep Thoughts',
    prompt: 'If your life had a soundtrack, what song would play during your current chapter?',
    type: 'text-input',
    points: 0,
    difficulty: 'chill',
    bothPlayers: true,
  },
  {
    id: 90,
    category: 'deep-thoughts',
    title: 'Deep Thoughts',
    prompt: 'What is a ridiculous dream you would genuinely love to achieve?',
    type: 'text-input',
    points: 0,
    difficulty: 'chill',
    bothPlayers: true,
  },

  // CHAOS (91-100)
  {
    id: 91,
    category: 'chaos',
    title: 'Chaos',
    prompt: 'Both players must answer the next question using only one word.',
    instructions: 'One word only. Make it count.',
    type: 'chaos',
    timer: 15,
    points: 50,
    difficulty: 'unhinged',
    bothPlayers: true,
  },
  {
    id: 92,
    category: 'chaos',
    title: 'Chaos',
    prompt: 'Point at the person who is most likely to accidentally become famous.',
    instructions: 'Physical action required!',
    type: 'chaos',
    points: 50,
    difficulty: 'unhinged',
    bothPlayers: true,
  },
  {
    id: 93,
    category: 'chaos',
    title: 'Chaos',
    prompt: 'Both players invent a new word. The other must guess what it means.',
    instructions: 'Be creative. Be weird.',
    type: 'chaos',
    timer: 20,
    points: 50,
    difficulty: 'unhinged',
    bothPlayers: true,
  },
  {
    id: 94,
    category: 'chaos',
    title: 'Chaos',
    prompt: 'You have 20 seconds to create a handshake.',
    instructions: 'Make it elaborate. Make it stick.',
    type: 'chaos',
    timer: 20,
    points: 75,
    difficulty: 'chaotic',
    bothPlayers: true,
  },
  {
    id: 95,
    category: 'chaos',
    title: 'Chaos',
    prompt: 'Rename the other player using only three words.',
    instructions: 'Go wild.',
    type: 'chaos',
    timer: 15,
    points: 50,
    difficulty: 'unhinged',
    bothPlayers: true,
  },
  {
    id: 96,
    category: 'chaos',
    title: 'Chaos',
    prompt: 'Both players create a superhero together. You have 30 seconds.',
    instructions: 'Name, powers, weakness. All of it.',
    type: 'chaos',
    timer: 30,
    points: 75,
    difficulty: 'unhinged',
    bothPlayers: true,
  },
  {
    id: 97,
    category: 'chaos',
    title: 'Chaos',
    prompt: 'Pick an ordinary object in the room. Explain why it is secretly extremely important.',
    instructions: 'You have 20 seconds. Be convincing.',
    type: 'chaos',
    timer: 20,
    points: 50,
    difficulty: 'chaotic',
    bothPlayers: false,
  },
  {
    id: 98,
    category: 'chaos',
    title: 'Chaos',
    prompt: 'Both players write the first thing that comes to mind. Reveal simultaneously.',
    instructions: 'No thinking. Pure instinct.',
    type: 'chaos',
    timer: 10,
    points: 50,
    difficulty: 'chaotic',
    bothPlayers: true,
  },
  {
    id: 99,
    category: 'chaos',
    title: 'Chaos',
    prompt: 'Create a completely fake conspiracy theory about something in the room.',
    instructions: 'You have 20 seconds. Be ridiculous.',
    type: 'chaos',
    timer: 20,
    points: 50,
    difficulty: 'unhinged',
    bothPlayers: false,
  },
  {
    id: 100,
    category: 'chaos',
    title: 'Chaos',
    prompt: 'Each player has 30 seconds to explain why THEY deserve to win the game.',
    instructions: 'FINAL BOSS MODE. Make your case.',
    type: 'chaos',
    timer: 30,
    points: 100,
    difficulty: 'unhinged',
    bothPlayers: true,
  },
]

export const WINNER_TITLES = [
  'THE MASTER OF CHAOS',
  'The HUMAN GOOGLE',
  'THE UNHINGED ORATOR',
  'THE GUESSING GURU',
  'THE DRAWING MENACE',
  'THE SUPREME OVERTHINKER',
  'The VIBE ARCHITECT',
  'THE CHAOS PROFESSOR',
  'The QUESTIONABLE GENIUS',
  'The FINAL BOSS',
  'THE PSYCHIC MIND-READER',
  'The ABSOLUTE LEGEND',
  'THE ANSWER WHISPERER',
  'The COMPETITIVE LEGEND',
  'THE LAUGHTER ENGINEER',
  'The MYSTERIOUS SAGE',
  'THE COSMIC OVERLORD',
  'The PURE VIBES EMBODIMENT',
]

export const FLAVOR_TEXTS = [
  'That answer was suspiciously confident.',
  'Your brain has entered another dimension.',
  'Absolutely nobody saw that coming.',
  'Interesting. Very interesting.',
  'That was either genius or terrible.',
  'Questionable decision detected.',
  'Your opponent knows you too well.',
  'That answer needs to be studied.',
  'The plot thickens.',
  'Unexpected turn of events.',
  'Peak performance unlocked.',
  'That\'s... bold.',
  'The vibes are immaculate.',
  'Chaos has entered the chat.',
  'Big brain energy.',
]

export const AVATARS = ['🙂', '😎', '👽', '👻', '🐸', '🤖', '🐱', '🦄', '🧠', '🛸', '🍄', '🌚']

export const PLAYER_COLORS = [
  '#ec4899', // pink
  '#06b6d4', // cyan
  '#a855f7', // purple
  '#22c55e', // green
  '#f59e0b', // amber
  '#ef4444', // red
]
